#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import shutil
from datetime import datetime, timezone
from pathlib import Path


ROOT_FILES = ("application.json", "metadata.json", "theme.json")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Regenerate the split Appsmith repo layout from a raw exported application JSON file."
    )
    parser.add_argument("export_json", help="Path to the raw exported Appsmith JSON file")
    parser.add_argument(
        "--repo-root",
        default=".",
        help="Path to the Appsmith git repo root (default: current directory)",
    )
    parser.add_argument(
        "--capture-dir",
        default="live-exports",
        help="Directory under the repo root for timestamped raw export captures",
    )
    return parser.parse_args()


def normalize(value):
    if isinstance(value, float) and value.is_integer():
        return int(value)
    if isinstance(value, list):
        return [normalize(item) for item in value]
    if isinstance(value, dict):
        return {key: normalize(item) for key, item in value.items()}
    return value


def write_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(normalize(payload), indent=2) + "\n", encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def strip_canvas_descendants(node: dict) -> dict:
    item = dict(node)
    item.pop("children", None)
    return item


def widget_file_payload(node: dict) -> dict:
    item = dict(node)
    children = item.get("children") or []
    if children:
        item["children"] = [strip_canvas_descendants(child) for child in children]
    else:
        item.pop("children", None)
    return item


def page_file_payload(page: dict) -> dict:
    unpublished = page["unpublishedPage"]
    layout = unpublished["layouts"][0]
    dsl = dict(layout["dsl"])
    dsl.pop("children", None)
    return {
        "gitSyncId": page["gitSyncId"],
        "unpublishedPage": {
            "isHidden": unpublished.get("isHidden", False),
            "layouts": [
                {
                    "layoutOnLoadActions": layout.get("layoutOnLoadActions", []),
                    "dsl": dsl,
                }
            ],
            "name": unpublished["name"],
            "slug": unpublished["slug"],
        },
    }


def datasource_file_payload(datasource: dict) -> dict:
    return {
        "gitSyncId": datasource["gitSyncId"],
        "isAutoGenerated": datasource.get("isAutoGenerated", False),
        "name": datasource["name"],
        "pluginId": datasource["pluginId"],
    }


def action_metadata_payload(action: dict) -> dict:
    unpublished = action["unpublishedAction"]
    datasource = unpublished["datasource"]
    action_config = dict(unpublished["actionConfiguration"])
    action_config.pop("selfReferencingDataPaths", None)
    return {
        "gitSyncId": action["gitSyncId"],
        "id": action["id"],
        "pluginId": action["pluginId"],
        "pluginType": action["pluginType"],
        "unpublishedAction": {
            "actionConfiguration": action_config,
            "confirmBeforeExecute": unpublished.get("confirmBeforeExecute", False),
            "datasource": {
                "id": datasource["name"],
                "isAutoGenerated": datasource.get("isAutoGenerated", False),
                "name": datasource["name"],
                "pluginId": datasource["pluginId"],
            },
            "dynamicBindingPathList": unpublished.get("dynamicBindingPathList", []),
            "name": unpublished["name"],
            "pageId": unpublished["pageId"],
            "runBehaviour": unpublished.get("runBehaviour", "MANUAL"),
            "userSetOnLoad": unpublished.get("userSetOnLoad", False),
        },
    }


def action_body_text(action: dict) -> str:
    return str(action["unpublishedAction"]["actionConfiguration"].get("body", ""))


def application_file_payload(data: dict) -> dict:
    exported = data["exportedApplication"]
    return {
        "appIsExample": exported.get("appIsExample", False),
        "appLayout": exported.get("publishedAppLayout", {}),
        "applicationVersion": exported.get("applicationVersion"),
        "collapseInvisibleWidgets": exported.get("collapseInvisibleWidgets", False),
        "color": exported.get("color"),
        "evaluationVersion": exported.get("evaluationVersion"),
        "pages": exported.get("pages", []),
        "unpublishedAppLayout": exported.get("unpublishedAppLayout", {}),
    }


def metadata_file_payload(data: dict, repo_root: Path) -> dict:
    existing = {}
    metadata_path = repo_root / "metadata.json"
    if metadata_path.exists():
        existing = json.loads(metadata_path.read_text(encoding="utf-8"))
    return {
        "artifactJsonType": data.get("artifactJsonType", "APPLICATION"),
        "clientSchemaVersion": data.get("clientSchemaVersion"),
        "fileFormatVersion": existing.get("fileFormatVersion", 5),
        "serverSchemaVersion": data.get("serverSchemaVersion"),
    }


def theme_file_payload(data: dict) -> dict:
    theme = data["editModeTheme"]
    return {
        "displayName": theme.get("displayName"),
        "isSystemTheme": theme.get("isSystemTheme", False),
        "name": theme.get("name"),
    }


def walk_widgets(node: dict, page_dir: Path, ancestors: list[str]) -> None:
    node_type = node.get("type")
    node_name = node.get("widgetName")
    children = node.get("children") or []

    if node_type == "CANVAS_WIDGET":
        for child in children:
            walk_widgets(child, page_dir, ancestors)
        return

    widget_rel_dir = page_dir / "widgets"
    if ancestors:
        widget_rel_dir = widget_rel_dir.joinpath(*ancestors)
    widget_file_dir = widget_rel_dir
    if children:
        widget_file_dir = widget_rel_dir / node_name
    write_json(widget_file_dir / f"{node_name}.json", widget_file_payload(node))

    next_ancestors = ancestors
    if children:
        next_ancestors = ancestors + [node_name]
    for child in children:
        walk_widgets(child, page_dir, next_ancestors)


def sync_export(export_path: Path, repo_root: Path, capture_dir: Path) -> None:
    data = json.loads(export_path.read_text(encoding="utf-8"))

    timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    capture_dir.mkdir(parents=True, exist_ok=True)
    capture_name = f"avondale-appsmith-live-export-{timestamp}.json"
    shutil.copy2(export_path, capture_dir / capture_name)

    for root_name in ("pages", "datasources", "jsobjects"):
        target = repo_root / root_name
        if target.exists():
            shutil.rmtree(target)
        target.mkdir(parents=True, exist_ok=True)

    write_json(repo_root / "application.json", application_file_payload(data))
    write_json(repo_root / "metadata.json", metadata_file_payload(data, repo_root))
    write_json(repo_root / "theme.json", theme_file_payload(data))

    for datasource in data.get("datasourceList", []):
        write_json(
            repo_root / "datasources" / f"{datasource['name']}.json",
            datasource_file_payload(datasource),
        )

    for page in data.get("pageList", []):
        page_name = page["unpublishedPage"]["name"]
        page_dir = repo_root / "pages" / page_name
        page_dir.mkdir(parents=True, exist_ok=True)
        write_json(page_dir / f"{page_name}.json", page_file_payload(page))

        root_dsl = page["unpublishedPage"]["layouts"][0]["dsl"]
        for child in root_dsl.get("children", []) or []:
            walk_widgets(child, page_dir, [])

    for action in data.get("actionList", []):
        page_name = action["unpublishedAction"]["pageId"]
        action_name = action["unpublishedAction"]["name"]
        action_dir = repo_root / "pages" / page_name / "queries" / action_name
        action_dir.mkdir(parents=True, exist_ok=True)
        write_json(action_dir / "metadata.json", action_metadata_payload(action))
        write_text(action_dir / f"{action_name}.txt", action_body_text(action))

    print(f"Stored raw export capture at {capture_dir / capture_name}")
    print(f"Regenerated split Appsmith repo files under {repo_root}")


def main() -> None:
    args = parse_args()
    repo_root = Path(args.repo_root).resolve()
    export_path = Path(args.export_json).resolve()
    capture_dir = (repo_root / args.capture_dir).resolve()
    sync_export(export_path, repo_root, capture_dir)


if __name__ == "__main__":
    main()
